# Generated by Django 3.2.14 on 2022-07-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doc',
        ),
    ]
