# Generated by Django 3.2.14 on 2022-07-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_pat1_appointment_pat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
